steps:
  - name: "gcr.io/cloud-builders/gcloud-slim"
    args: ["container", "clusters", "get-credentials", "demo",
           "--zone", "europe-west1-b", "--project", "next19"]
  - name: "gcr.io/next19/skaffold"
    args: ["skaffold", "run", "-p", "color"]
