apiVersion: apps/v1
kind: Deployment
metadata:
  name: colors
  labels:
    app: colors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colors
  template:
    metadata:
      labels:
        app: colors
    spec:
      containers:
      - name: colors
        imagePullPolicy: Always
        image: gcr.io/next19/colors
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: colors
spec:
  type: LoadBalancer
  selector:
    app: colors
  ports:
  - port: 8888
    targetPort: 8888
